graph TD
    Dapper --> System.Reflection.Emit.Lightweight_4.7.0
    System.Reflection.Emit.Lightweight_4.7.0 --> System.Reflection_4.3.0
    System.Reflection.Emit.Lightweight_4.7.0 --> System.Reflection.Emit.ILGeneration_4.7.0
    System.Reflection.Emit.Lightweight_4.7.0 --> System.Reflection.Primitives_4.3.0
    System.Reflection.Emit.Lightweight_4.7.0 --> System.Resources.ResourceManager_4.3.0
    System.Reflection.Emit.Lightweight_4.7.0 --> System.Runtime_4.3.0
    System.Reflection_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Reflection_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Reflection_4.3.0 --> System.IO_4.3.0
    System.Reflection_4.3.0 --> System.Reflection.Primitives_4.3.0
    System.Reflection_4.3.0 --> System.Runtime_4.3.0
    System.IO_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.IO_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.IO_4.3.0 --> System.Runtime_4.3.0
    System.IO_4.3.0 --> System.Text.Encoding_4.3.0
    System.IO_4.3.0 --> System.Threading.Tasks_4.3.0
    System.Runtime_4.3.0 --> Microsoft.NETCore.Platforms_1.1.1
    System.Runtime_4.3.0 --> Microsoft.NETCore.Targets_1.1.3
    System.Text.Encoding_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Text.Encoding_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Text.Encoding_4.3.0 --> System.Runtime_4.3.0
    System.Threading.Tasks_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Threading.Tasks_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Threading.Tasks_4.3.0 --> System.Runtime_4.3.0
    System.Reflection.Primitives_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Reflection.Primitives_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Reflection.Primitives_4.3.0 --> System.Runtime_4.3.0
    System.Reflection.Emit.ILGeneration_4.7.0 --> System.Reflection_4.3.0
    System.Reflection.Emit.ILGeneration_4.7.0 --> System.Reflection.Primitives_4.3.0
    System.Reflection.Emit.ILGeneration_4.7.0 --> System.Resources.ResourceManager_4.3.0
    System.Reflection.Emit.ILGeneration_4.7.0 --> System.Runtime_4.3.0
    System.Resources.ResourceManager_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Resources.ResourceManager_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Resources.ResourceManager_4.3.0 --> System.Globalization_4.3.0
    System.Resources.ResourceManager_4.3.0 --> System.Reflection_4.3.0
    System.Resources.ResourceManager_4.3.0 --> System.Runtime_4.3.0
    System.Globalization_4.3.0 --> Microsoft.NETCore.Platforms_1.1.0
    System.Globalization_4.3.0 --> Microsoft.NETCore.Targets_1.1.0
    System.Globalization_4.3.0 --> System.Runtime_4.3.0
